### PR TITLE
Add Message.custom

### PR DESCRIPTION
**Pull request by HuyaneMatsu**
Fixes:
- Register wrapped generators as coroutines as well. (Submitted by Proxy)
- `Permission.update_by_keys` always returned a bad value >.>

Changes:
- `loop` argument for `sleep` is optional.

New:
- Add `Message.custom`.

And some small stuffs, have a great day.

### CODE REVIEW

**Comment by gsbhasin123** [comment]
Um @HuyaneMatsu 
Why'd you open a PR for your own lib?

**Comment by HuyaneMatsu** [comment]
So I can merge dev to Master. Or am I doing something wrong?

**Comment by gsbhasin123** [comment]
Oh. never mind.
There is a `git merge` command, btw

**Comment by HuyaneMatsu** [comment]
Good to know :yayy:

**Comment by gsbhasin123** [comment]
Lol

**Comment by gsbhasin123** [comment]
:yin_yang:

**Pull request merged**
